-- =====================================================================
-- DATABASE SCRIPT: CUSTOMER MANAGEMENT SYSTEM (V3 - POSTGRESQL COMPATIBLE)
-- TARGET DATABASE: PostgreSQL 10+ / ANSI SQL Compliant
-- ARCHITECTURE: CENTRALIZED ACCOUNT - DISTRIBUTED TENANT POINT & VOUCHER
-- =====================================================================

-- 1. Bảng Khách hàng tập trung (Hệ thống SaaS dùng chung toàn nền tảng để định danh)
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    phone VARCHAR(15) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_customer_phone UNIQUE (phone)
);

COMMENT ON TABLE customers IS 'Bảng lưu trữ thông tin tài khoản khách hàng tập trung toàn hệ thống';
COMMENT ON COLUMN customers.id IS 'ID duy nhất của khách hàng toàn hệ thống';
COMMENT ON COLUMN customers.phone IS 'Số điện thoại dùng để đăng nhập và định danh chính';
COMMENT ON COLUMN customers.status IS 'Trạng thái tài khoản: ACTIVE (Hoạt động), LOCKED (Bị khóa bởi Manager)';

-- 2. Bảng Ví điểm phân tán theo Nhà hàng (Cốt lõi xử lý Multi-tenant logic)
CREATE TABLE IF NOT EXISTS customer_point (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id BIGINT NOT NULL,
    restaurant_id BIGINT NOT NULL,
    current_points INT NOT NULL DEFAULT 0,
    lifetime_points INT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_customer_restaurant UNIQUE (customer_id, restaurant_id),
    CONSTRAINT fk_customer_point_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE
);

COMMENT ON TABLE customer_point IS 'Bảng quản lý số dư điểm thưởng độc lập của khách hàng theo từng nhà hàng';

-- 3. Bảng Cấu hình Voucher & Luật đổi điểm của Quán
CREATE TABLE IF NOT EXISTS vouchers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    restaurant_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    discount_percent INT NOT NULL,
    min_bill_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    points_required INT NOT NULL DEFAULT 0,
    is_active SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT chk_voucher_discount CHECK (discount_percent BETWEEN 1 AND 100)
);

COMMENT ON TABLE vouchers IS 'Bảng chứa các khuôn mẫu Voucher kèm luật đổi điểm tích lũy riêng của từng nhà hàng';

-- 4. Bảng Ví mã Voucher cá nhân của Khách hàng
CREATE TABLE IF NOT EXISTS customer_vouchers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id BIGINT NOT NULL,
    restaurant_id BIGINT NOT NULL,
    voucher_id BIGINT NOT NULL,
    voucher_sn VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    used_at TIMESTAMP DEFAULT NULL,
    order_id BIGINT DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_voucher_sn UNIQUE (voucher_sn),
    CONSTRAINT fk_cv_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE,
    CONSTRAINT fk_cv_voucher FOREIGN KEY (voucher_id) REFERENCES vouchers (id) ON DELETE CASCADE
);

COMMENT ON TABLE customer_vouchers IS 'Ví voucher lưu trữ chi tiết các tờ phiếu giảm giá thực tế mà từng khách đang sở hữu';

-- 5. Bảng Nhật ký biến động điểm thưởng (Đối soát lịch sử)
CREATE TABLE IF NOT EXISTS customer_point_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id BIGINT NOT NULL,
    restaurant_id BIGINT NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    points_changed INT NOT NULL,
    reference_id BIGINT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_history_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE
);

COMMENT ON TABLE customer_point_history IS 'Bảng ghi nhật ký lịch sử cộng/trừ điểm thưởng phục vụ cả App Khách và Web Manager';

-- 6. Bảng Đánh giá & Phản hồi (Feedback liên kết trực tiếp với Đơn hàng)
CREATE TABLE IF NOT EXISTS feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id BIGINT NOT NULL,
    restaurant_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    rating_food INT NOT NULL,
    rating_service INT NOT NULL,
    comment TEXT DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_feedback_order UNIQUE (order_id),
    CONSTRAINT fk_feedback_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE,
    CONSTRAINT chk_rating_food CHECK (rating_food BETWEEN 1 AND 5),
    CONSTRAINT chk_rating_service CHECK (rating_service BETWEEN 1 AND 5)
);

COMMENT ON TABLE feedbacks IS 'Bảng lưu trữ đánh giá sao và phản hồi xử lý khủng hoảng của chi nhánh';